spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.1.91:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 753951
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:generator/*.xml
logging:
  level:
    com.zimug.bootlaunch: debug
